stages:
  - test
  - publish

test:
  stage: test
  image: sbtscala/scala-sbt:graalvm-ce-22.3.3-b1-java17_1.12.3_3.3.7
  variables:
    SBT_TPOLECAT_CI: 1
  cache:
    key: "$CI_PROJECT_NAME"
    paths:
      - .ivy2
  script:
    - sbt -ivy .ivy2 "clean; test"

publish:
  stage: publish
  image: sbtscala/scala-sbt:graalvm-ce-22.3.3-b1-java17_1.12.3_3.3.7
  cache:
    key: "$CI_PROJECT_NAME"
    paths:
      - .ivy2
  script:
    - sbt -ivy .ivy2 "publish"
  except:
   - tags