stages:
  - test
  - publish

test:
  stage: test
  image: hseeberger/scala-sbt:graalvm-ce-20.0.0-java11_1.3.13_2.13.3
  variables:
    SCALA_VERSION: 2.13.3
  cache:
    key: "$CI_PROJECT_NAME"
    paths:
      - .ivy2
  script:
    - sbt -ivy .ivy2 clean test

publish:
  stage: publish
  image: hseeberger/scala-sbt:graalvm-ce-20.0.0-java11_1.3.13_2.13.3
  cache:
    key: "$CI_PROJECT_NAME"
    paths:
      - .ivy2
  script:
    - sbt -ivy .ivy2 publish