rules =
[ NoAutoTupling
, OrganizeImports
, LeakingImplicitClassVal
, NoValInForComprehension
, RedundantSyntax
, RemoveUnused
]

OrganizeImports.preset = INTELLIJ_2020_3
# breaks compilation
OrganizeImports.coalesceToWildcardImportThreshold = null
OrganizeImports.importSelectorsOrder = Keep
